language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-chroma-fund-package' ]; then cd .. && eval "mv $currentfolder generator-chroma-fund-package" && cd generator-chroma-fund-package; fi
